
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP주소 등록
  client:
    registerWithEureka: true # 유레카에 서비스 등록
    fetchRegistry: true # 유레카 서비스 위치(클라이언트가 레지스트의 로컬 복사본을 가져오도록 지정 - 유레카 호출 대신 로컬 캐시 사용하고, 30초 주기로 갱싱
    serviceUrl:
        defaultZone: http://localhost:8761/eureka/ # ,로 구분하여 n개의 유레카 서비스를 등록 가능

        